### PR TITLE
Web3Auth Example with AngularJS

### PR DESCRIPTION
**Pull request by tainguyentt**

### CODE REVIEW

**Comment by tainguyentt** [comment]
Hi @chaitanyapotti could you help to review it? I have attached some screenshots in the ticket https://toruslabs.atlassian.net/browse/FD-705. Thanks

**Comment by tainguyentt** [comment]
image
image
image

**Comment by tainguyentt** [comment]
image
image

**Comment by tainguyentt** [comment]
Hi @chaitanyapotti I have updated the AngularJS example. Pls help to review the change. Thanks

**Review by chaitanyapotti — APPROVED** [review]
lgtm

**Pull request merged**
