### PR TITLE
added whitelabel example

### PR DESCRIPTION
**Pull request by lionellbriones**
What does this PR do?
This app showcase a customizable UI for web3auth. Running the app generates example configuration code.

### CODE REVIEW

**Comment by himanshuchawla009** [comment]
This looks like a good start for showing generated code. I have noticed a few things which can be improved.

1. Code for showing generated code and actual web3auth functionality should be decoupled. Currently, both are mixed up so it will be tough for developers to go through example code. 

2. Also we should show more generated code along with vue data and methods. Generated Code should be copied pastable by the user.


I am working on both of these things @lionellbriones

**Review by himanshuchawla009 — CHANGES_REQUESTED** [review]
This looks like a good start for showing generated code. I have noticed a few things which can be improved.

Code for showing generated code and actual web3auth functionality should be decoupled. Currently, both are mixed up so it will be tough for developers to go through example code.

Also we should show more generated code along with vue data and methods. Generated Code should be copied pastable by the user.

I am working on both of these things @lionellbriones

**Comment by himanshuchawla009** [comment]
updated on above suggestions.

Screenshot 2022-02-28 at 6 58 57 PM

**Comment by chaitanyapotti** [comment]
Not using this anymore

**Pull request closed without merging**
